name: thanos_snap_effect
description: 'High-performance, high-customizable, and easy-to-use "Thanos Snap" effect for Flutter.'
version: 0.0.6
homepage: https://github.com/ArkhipenkaPiotr/thanos_snap_effect

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
