name: PR run analyze and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check_format_and_analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          channel: stable
          version: 3.2.0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install dependencies
        run: dart pub get

      - name: check format
        run: dart format --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze